### ISSUE TITLE
Add Help/About/User Guide link to the PathLinker app documentation

### ISSUE THREAD

**Issue by jlaw9** [Murali-group/PathLinker-Cytoscape#1]
A lot of the other apps have a help or about or user guide button which has a link to the help page. There should probably be a link to the cytoscape page http://apps.cytoscape.org/apps/pathlinker in the PathLinker app itself.

**Comment by jlaw9** [comment]
@tmmurali should we now request that people cite the F1000 PathLinker app paper on the PathLinker app page http://apps.cytoscape.org/apps/pathlinker instead of the PathLinker and Linker papers?

**Comment by tmmurali** [comment]
On Tue, Aug 15, 2017 at 11:04 AM, Jeff Law <notifications@github.com> wrote:

> @tmmurali <https://github.com/tmmurali> should we now request that people
> cite the F1000 PathLinker app paper on the PathLinker app page
> http://apps.cytoscape.org/apps/pathlinker instead of the PathLinker and
> Linker papers?
>

We can request that people cite the papers in F1000 Research and in Systems
Biology and Applications. We can remove the JCB paper.

**Comment by jlaw9** [comment]
sounds good. Thanks

**Comment by jlaw9** [comment]
We should move the help option to the PathLinkerControlPanel as a button. Probably in the top right. We should also move the close button to the top right.

Murali suggested to not have the open/close options in the apps dropdown section, but to open PathLinker automatically when the app is clicked. 

Also, in the About section, change the date to have the abbreviation of the month
