### ISSUE TITLE
Feature request - load selected nodes

### ISSUE THREAD

**Issue by agitter** [Murali-group/PathLinker-Cytoscape#11]
It would be useful to be able to populate the Sources and Targets fields from the set of nodes that are selected in the Cytoscape network.  This would make it easier for non-programmers to load different node attributes, select nodes based on those attributes, and then load the selected nodes as sources or targets.

**Comment by jlaw9** [comment]
We can get the selected nodes using the function shown in the sample app [sample-get-selected-nodes](https://github.com/cytoscape/cytoscape-app-samples/blob/master/sample-get-selected-nodes/src/main/java/org/cytoscape/sample/internal/GetSelectedNodesAction.java). We should then be able to add a button to add the selected nodes to the sources and populate the sources list and then do the same for the targets.
