### ISSUE TITLE
Provide appropriate error message if the user has not selected a network

### ISSUE THREAD

**Issue by tmmurali** [Murali-group/PathLinker-Cytoscape#15]
If the user runs the PathLinker app without loading a network, i.e., the user fills in the parameters such as sources, targets, and k, the app provides an uninformative error message:

"There are no valid sources to be used. Quitting."

The app should check if there is no network selected and request the user to load one.

**Comment by jlaw9** [comment]
The error message is now "Network not found. Please load a valid network"
