### ISSUE TITLE
Add unit tests 

### ISSUE THREAD

**Issue by jlaw9** [Murali-group/PathLinker-Cytoscape#22]
With the changes I'm making to the underlying algorithm, it would be helpful to have tests set up to ensure nothing is broken by an update. It would also be very helpful if we added a time test to make sure the code isn't taking too long.

It looks like we can model our tests after the some of the cytoscape tests (like [this one](    https://github.com/cytoscape/cytoscape-impl/blob/e675aaca6b29f3b108b4bf51f5943b9aab00eedc/core-task-impl/src/test/java/org/cytoscape/task/internal/creation/NewNetworkSelectedNodesEdgesTaskTest.java
) for example) 

Functionalities to test:
- [x] Directed, undirected and mixed input networks
- [x] Sources/Targets options
- [x] Edge weight options: Unweighted, weighted additive, and weighted probabilites
- [x] ~~Varying values of k~~
- [x] ~~Edge penalty (for additive and probabilities)~~

**Comment by jlaw9** [comment]
The unit tests should be of the main `runKSP()` function in the PathLinkerPanel.java file.

**Comment by jlaw9** [comment]
@tmmurali All of the methods we need to test in PathLinkerPanel.java are currently private which doesn't allow them to be called from a unit test. The first function that is called after pressing the "submit" button in cytoscape is `prepareAndRunKSP()`. That function call `runKSP()` which handles all of the inputs, algorithm running, and outputs. We need to either change parepareAndRunKSP or runKSP to be public, or make some other design changes such as create a separate class for  runKSP.

What do you think?

**Comment by tmmurali** [comment]
OK with me.

**Comment by jlaw9** [comment]
We decided specific tests for k and an edge penalty were not needed. 

I'm leaving this issue open because the testAllowSourceTargetInPaths() test case is not yet set up correctly. It is currently only testing a k of 13. PathLinker does not have the option of using a source-source or target-target edge in a path at low k-values. This test either needs to use higher k-values, or a smaller network that tests this option explicitly.
