### ISSUE TITLE
Sort PathLinker results

### ISSUE THREAD

**Issue by jlaw9** [Murali-group/PathLinker-Cytoscape#28]
For paths where the path score is the same, it is cleaner for the paths to be sorted in alphabetical order. 

This is also beneficial for the unit testing as it ensures that the output paths will be the same each run. Otherwise the paths can be output in an arbitrary order and we would have to sort the paths to compare against the test anyway. 

Perhaps we should add an "include ties" option to allow the user to include paths of the same path score that is cut off by k.

**Comment by jlaw9** [comment]
In order add the path index to the edge table #4, the results need to be sorted earlier than the ResultFrame class.

**Comment by LHuang2019** [comment]
The plan is to implement a LinkedHashMap to Path class so that it has access to the string node name directly without needing the originalNetwork. Then we can implement the comparable to the Path class for sorting purposes.

**Comment by jlaw9** [comment]
Ultimately Li decided to add a map from the node ID to the node name to each Path object to access the node name for sorting.
