### ISSUE TITLE
Change the default color of PathLinker targets

### ISSUE THREAD

**Issue by jlaw9** [Murali-group/PathLinker-Cytoscape#3]
The yellow color of the targets is the same color as when you select a node which could be confusing to users in some cases. Probably a different shade of yellow would be fine.

**Comment by dpgil** [comment]
Changed it to more of a gold color, rgb(255,223,0). I attached a screenshot of the new color, with the top left node selected to see the difference. Let me know what you think

![image](https://cloud.githubusercontent.com/assets/7670571/16939395/12a7e540-4d36-11e6-9a90-0ae7f3214112.png)

**Comment by jlaw9** [comment]
Looks good to me
