### ISSUE TITLE
Add the path index to the edge table

### ISSUE THREAD

**Issue by jlaw9** [Murali-group/PathLinker-Cytoscape#4]
Each edge in the output network should be annotated or associated with the index of the first path in which that each edge appears.

This will be useful for uploading cytoscape json files to graphspace to allow for the k slider.

**Comment by LHuang2019** [comment]
This issue should be work on only after the path results are correctly sorted. relates to issue #29.

**Comment by jlaw9** [comment]
@LHuang2019 why is that?

**Comment by jlaw9** [comment]
Currently the column is titled "path index n" where a new column is created, incrementing n each time, for each additional PathLinker run
