### ISSUE TITLE
Sync naming and deletion of subnetwork, results and path index column

### ISSUE THREAD

**Issue by jlaw9** [Murali-group/PathLinker-Cytoscape#46]
Right now the subnetwork, results and path rank outputs are all named separately from each other. If the user deletes one these and then generates more results, they could get out of sync from each other (meaning a result PathLinker Results 6 could be paired with the Path Rank 5 and PathLinker-results-2-50-paths sub-network).

We should make sure the subnetwork, results and path index column from a PathLinker run all have the same number.

- Subnetwork name: `PathLinker-results-X-200-paths`
- Results panel name: `PathLinker Results X`
- Path rank column name: `path-rank-X`

We also want to add the option to delete all three of these results generated by a PathLinker run. Upon clicking the 'Delete' button, the user will have the following message with 3 options:

Warning:
Delete this panel "PathLinker Results X" or delete all results: "PathLinker Result X, Path Rank X, and Subnetwork X". Deleted results will be permanently removed. 

1. Cancel
2. Delete This Panel
3. Delete All Results

**Comment by jlaw9** [comment]
When the PathLinker results panel is discarded, the corresponding path index and subnetwork should also be deleted. This will help keeps things in sync. The warning message should warn the user accordingly.

**Comment by jlaw9** [comment]
To sync the results number, we can store an integer internally and increment it every time the app is run successfully.

**Comment by jlaw9** [comment]
Li said he is able to store the SUID of the subnetwork we generate so that it can also be deleted when the "Delete" button is pressed on the Results Panel. However Li cannot delete the "Path Rank X" column we generate by an ID, only by the name of the column.

This leads to potential problems because the user could rename the column meaning it won't be deleted. 

Li suggests we don't delete the Path Rank X column to avoid possible confusion for the user.

I vote we just keep the warning message above and delete the column according to the expected name if it exists. I think it will be more beneficial to users to not have too many accumulating columns in the Node table and I doubt any users will have a problem with it. It's easy enough to re-run PathLinker with the same settings if they run into any problems.

@tmmurali What do you think?

**Comment by tmmurali** [comment]
The warning itself is unclearly phrased.  I suggest the following:

Would you like to delete this panel "PathLinker Results X" or delete all results: "PathLinker Result X, Path Rank X, and Subnetwork X"? Note that you will need to rerun PathLinker to regenerate the deleted results.

After having said this, the flow seems wrong. If the user sees a delete button, presses it, and then sees a warning with two choices, why not just present the two delete choices as separate buttons?

**Comment by jlaw9** [comment]
We decided to have a single delete button in the Results Panel that will delete all three results. Here's the message:
![image](https://user-images.githubusercontent.com/7592559/32847474-17cfe834-c9f8-11e7-9788-f031e7bda36a.png)

**Comment by tmmurali** [comment]
I would change the voice to active. "This action will delete the following
items permanently:"

>
