### ISSUE TITLE
PathLinker incompatible with Cytoscape 3.6

### ISSUE THREAD

**Issue by LHuang2019** [Murali-group/PathLinker-Cytoscape#58]
When generating a sub-network with PathLinker on Cytoscape 3.6, the process is stopped with: 
`Unexpected exception with handling listener.
org.cytoscape.model.events.RowsSetListener`

The generated sub-network is shown without the correct style and the result panel does not show up.

Update:

The above problem is temporary fixed by revert back to the hack of selecting newly created sub-network and sub-network views through looping.

But another problem shows up where hierarchical layout is unable to be applied to the new sub-network view.

**Comment by jlaw9** [comment]
Fixed by PR #61
