### ISSUE TITLE
PathLinker fails to start with Cytoscape 3.7+

### ISSUE THREAD

**Issue by LHuang2019** [Murali-group/PathLinker-Cytoscape#67]
Unable to load PathLinker app when starting Cytoscape 3.7.

**Comment by jlaw9** [comment]
I put this message on the app store page (http://apps.cytoscape.org/apps/pathlinker) for now:

Alert for users of Cytoscape v3.7+!
When opening Cytoscape v3.7+, the PathLinker app fails to start. We are still looking into why that is, but for now, you can get the app to start by opening the App manager (Apps -> App manager from the menubar within Cytoscape), and then disabling and enabling the app, or uninstalling and reinstalling the app. These steps need to be repeated every time Cytoscape is restarted.

**Comment by LHuang2019** [comment]
Issue follow-up on the [cytoscape google group](https://groups.google.com/forum/#!topic/cytoscape-app-dev/ZMlOszClLmc).
