### ISSUE TITLE
Does PathLinker support two edges with opposite directions for the same node pair?

### ISSUE THREAD

**Issue by michaelpierrelee** [Murali-group/PathLinker-Cytoscape#70]
Dear authors,

According to some comments in the PathLinker code, multi-edges are not supported and, if there are two edges between A and B, one will be arbitrary taken.

I'm wondering if PathLinker supports two edges with opposite directions for the same node pair. In other words, for a directed network, if the edge "A -> B" is compatible with the edge "B -> A".

Thanks,
Michaël

**Comment by tmmurali** [comment]
Sorry for the late reply. Yes, PathLinker will treat these edges as distinct, simply as a consequence of the underlying network data structure used.

The comment may refer to a multigraph, where multiple directed edges may have the same tail and head, e.g., different types of edges all directed from node a to node b.
