### ISSUE TITLE
PathLinker GUI (cytoscape panel) not working on Cytoscape 3.8

### ISSUE THREAD

**Issue by michaelpierrelee** [Murali-group/PathLinker-Cytoscape#71]
Hi,

The PathLinker GUI (Cytoscape panel on the left side) is bugging on the newest Cytoscape version (3.8 in Java 11). However, its CyREST interface is working well.

Thanks

**Comment by olhakholod** [comment]
Have the same issue with PathLinker GUI.

**Comment by jlaw9** [comment]
Thank you for bringing this to our attention and apologies for the delay. The app is now updated to work on the newest Cytoscape version (3.8+).

**Comment by jlaw9** [comment]
@michaelpierrelee and @olhakholod I should also mention that I made a change to how the app is run. For some reason the approach we were using to launch the app when selecting it from the 'Apps' drop-down menu was buggy with Cytoscape v3.8+ so to circumvent that problem, the app now starts automatically as soon as Cytoscape starts. I'll update this issue if we figure out the problem and decide to bring back that functionality.
